language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script:
  - composer self-update
  - composer install -n

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.0' ]]; then ./vendor/bin/phpunit --coverage-clover=coverage.clover ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '7.0' ]]; then ./vendor/bin/phpunit ; fi

after_success:
    - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
