language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - composer self-update
  - composer install -n

script:
  - ./vendor/bin/phpunit