language: php

php:
  - 7.3
  - 7.4

before_script:
  - composer self-update
  - composer install -n

script:
  - if [[ "$TRAVIS_PHP_VERSION" == '7.1' ]]; then ./vendor/bin/phpunit --coverage-clover=coverage.clover ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != '7.1' ]]; then ./vendor/bin/phpunit ; fi

after_success:
    - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ "$TRAVIS_PHP_VERSION" == "7.1" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
